// ====================================================================
// Payment webhook verification tests
// ====================================================================

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import crypto from "crypto";
import {
  verifyHmac,
  verifyMoyasarWebhook,
  verifyTapWebhook,
  extractTapFields,
  buildTapHashstring,
  formatTapAmount,
  verifyAmount,
  verifyCurrency,
  verifyPaymentMetadata,
  isGatewayConfigured,
  isAlreadyPaid,
} from "@/lib/services/webhook-verify";

describe("webhook: HMAC verification", () => {
  const secret = "test-secret-32chars-long-aaaaaaaa";
  const body = JSON.stringify({
    id: "pay_123",
    status: "paid",
    amount: 89900,
    currency: "SAR",
  });

  it("accepts a valid HMAC signature", () => {
    const sig = crypto.createHmac("sha256", secret).update(body).digest("hex");
    expect(verifyHmac(sig, secret, body, "sha256")).toBe(true);
  });

  it("rejects an invalid HMAC signature", () => {
    expect(verifyHmac("deadbeef", secret, body, "sha256")).toBe(false);
  });

  it("rejects when signature is missing", () => {
    expect(verifyHmac(undefined, secret, body, "sha256")).toBe(false);
    expect(verifyHmac(null, secret, body, "sha256")).toBe(false);
    expect(verifyHmac("", secret, body, "sha256")).toBe(false);
  });

  it("rejects when secret is missing (fail closed)", () => {
    const sig = crypto.createHmac("sha256", secret).update(body).digest("hex");
    expect(verifyHmac(sig, "", body, "sha256")).toBe(false);
    expect(verifyHmac(sig, undefined as any, body, "sha256")).toBe(false);
  });

  it("is constant-time — same-length signatures still reject", () => {
    // Different content but same length
    const sig1 = crypto.createHmac("sha256", secret).update(body).digest("hex");
    const sig2 = "a".repeat(sig1.length);
    expect(verifyHmac(sig2, secret, body, "sha256")).toBe(false);
  });
});

describe("webhook: Moyasar signature verification", () => {
  const secret = "moyasar-wh-secret-32-chars-long";
  const body = '{"id":"pay_1","status":"paid"}';

  it("accepts a valid Moyasar signature", () => {
    const sig = crypto.createHmac("sha256", secret).update(body).digest("hex");
    expect(verifyMoyasarWebhook(body, sig, secret)).toBe(true);
  });

  it("rejects when no secret configured (fail closed)", () => {
    const sig = crypto.createHmac("sha256", secret).update(body).digest("hex");
    expect(verifyMoyasarWebhook(body, sig, undefined)).toBe(false);
  });

  it("rejects unsigned webhooks", () => {
    expect(verifyMoyasarWebhook(body, undefined, secret)).toBe(false);
    expect(verifyMoyasarWebhook(body, "", secret)).toBe(false);
  });
});

// ====================================================================
// Tap webhook — official hashstring verification tests
// Per https://www.tap.company/docs/en/webhooks
// ====================================================================

// Fixture matching Tap's OFFICIAL charge object shape:
//   reference.gateway   (x_gateway_reference — can be absent → "")
//   reference.payment   (x_payment_reference — required)
//   transaction.created (x_created — NOT top-level created)
const tapChargeFixture = {
  id: "chg_TS01A3BCDEFG",
  amount: 100.00,
  currency: "SAR",
  reference: {
    gateway: "87654321",
    payment: "pay_2024ABCDE",
    order: "ord_2024XYZ",
  },
  status: "CAPTURED",
  transaction: {
    created: "2024-12-15T10:30:00.000Z",
  },
};

// Fixture with empty gateway_reference (allowed by Tap docs)
const tapChargeFixtureEmptyGateway = {
  ...tapChargeFixture,
  reference: {
    payment: "pay_2024ABCDE",
    order: "ord_2024XYZ",
    // gateway intentionally absent
  },
};

// Manually-written expected hashstring (NOT generated by buildTapHashstring)
// Per Tap docs: x_id${id}x_amount${amount}x_currency${currency}x_gateway_reference${gateway}x_payment_reference${payment}x_status${status}x_created${created}
// amount formatted to 2 decimal places: 100.00
const EXPECTED_TAP_HASHSTRING =
  "x_idchg_TS01A3BCDEFG" +
  "x_amount100.00" +
  "x_currencySAR" +
  "x_gateway_reference87654321" +
  "x_payment_referencepay_2024ABCDE" +
  "x_statusCAPTURED" +
  "x_created2024-12-15T10:30:00.000Z";

// Manually-written expected hashstring for empty gateway_reference
const EXPECTED_TAP_HASHSTRING_EMPTY_GATEWAY =
  "x_idchg_TS01A3BCDEFG" +
  "x_amount100.00" +
  "x_currencySAR" +
  "x_gateway_reference" + // gateway is "" — nothing after the prefix
  "x_payment_referencepay_2024ABCDE" +
  "x_statusCAPTURED" +
  "x_created2024-12-15T10:30:00.000Z";

describe("webhook: Tap hashstring construction", () => {
  it("formats SAR amount to 2 decimal places", () => {
    expect(formatTapAmount(100)).toBe("100.00");
    expect(formatTapAmount(100.0)).toBe("100.00");
    expect(formatTapAmount(100.5)).toBe("100.50");
    expect(formatTapAmount("100.25")).toBe("100.25");
  });

  it("handles zero amount", () => {
    expect(formatTapAmount(0)).toBe("0.00");
  });

  it("rejects non-finite amounts", () => {
    expect(formatTapAmount(NaN)).toBe("0.00");
    expect(formatTapAmount(Infinity)).toBe("0.00");
    expect(formatTapAmount("abc")).toBe("0.00");
  });

  it("builds the EXACT hashstring per Tap docs (literal concatenation, NOT join)", () => {
    const fields = extractTapFields(tapChargeFixture)!;
    const hashstring = buildTapHashstring(fields);
    // Compare against a MANUALLY-written expected string — NOT generated
    // by the same function we are testing.
    expect(hashstring).toBe(EXPECTED_TAP_HASHSTRING);
  });

  it("builds correct hashstring when gateway_reference is empty (allowed by Tap)", () => {
    const fields = extractTapFields(tapChargeFixtureEmptyGateway)!;
    const hashstring = buildTapHashstring(fields);
    expect(hashstring).toBe(EXPECTED_TAP_HASHSTRING_EMPTY_GATEWAY);
  });
});

describe("webhook: Tap field extraction (official shape)", () => {
  it("extracts all required fields from Tap's official charge shape", () => {
    const fields = extractTapFields(tapChargeFixture);
    expect(fields).not.toBeNull();
    expect(fields!.id).toBe("chg_TS01A3BCDEFG");
    expect(fields!.amount).toBe(100.00);
    expect(fields!.currency).toBe("SAR");
    expect(fields!.gateway_reference).toBe("87654321");
    expect(fields!.payment_reference).toBe("pay_2024ABCDE");
    expect(fields!.status).toBe("CAPTURED");
    expect(fields!.created).toBe("2024-12-15T10:30:00.000Z");
  });

  it("extracts gateway_reference from reference.gateway (NOT flat gateway_reference)", () => {
    const fields = extractTapFields(tapChargeFixture);
    expect(fields!.gateway_reference).toBe("87654321");
  });

  it("extracts payment_reference from reference.payment (NOT reference.transaction)", () => {
    const fields = extractTapFields(tapChargeFixture);
    expect(fields!.payment_reference).toBe("pay_2024ABCDE");
  });

  it("extracts created from transaction.created (NOT top-level created)", () => {
    const fields = extractTapFields(tapChargeFixture);
    expect(fields!.created).toBe("2024-12-15T10:30:00.000Z");
  });

  it("allows missing gateway_reference (defaults to empty string)", () => {
    const fields = extractTapFields(tapChargeFixtureEmptyGateway);
    expect(fields).not.toBeNull();
    expect(fields!.gateway_reference).toBe("");
  });

  it("returns null if payment_reference is missing", () => {
    expect(
      extractTapFields({
        ...tapChargeFixture,
        reference: { gateway: "87654321" }, // no payment
      })
    ).toBeNull();
  });

  it("returns null if transaction.created is missing", () => {
    expect(
      extractTapFields({
        ...tapChargeFixture,
        transaction: {}, // no created
      })
    ).toBeNull();
  });

  it("returns null if id, amount, currency, or status is missing", () => {
    expect(extractTapFields({ id: "x" })).toBeNull();
    expect(extractTapFields({ ...tapChargeFixture, id: null })).toBeNull();
    expect(extractTapFields({ ...tapChargeFixture, amount: undefined })).toBeNull();
    expect(extractTapFields({ ...tapChargeFixture, currency: undefined })).toBeNull();
    expect(extractTapFields({ ...tapChargeFixture, status: undefined })).toBeNull();
    expect(extractTapFields(null)).toBeNull();
    expect(extractTapFields("string")).toBeNull();
  });
});

describe("webhook: Tap signature verification (hashstring method)", () => {
  const tapSecretKey = "sk_test_XXXXXXXXXXXXXXXXXXXXXX"; // TAP_SECRET_KEY

  it("accepts a valid Tap hashstring signature", () => {
    const fields = extractTapFields(tapChargeFixture)!;
    const hashstring = buildTapHashstring(fields);
    const sig = crypto.createHmac("sha256", tapSecretKey).update(hashstring).digest("hex");
    expect(verifyTapWebhook(tapChargeFixture, sig, tapSecretKey)).toBe(true);
  });

  it("accepts a valid signature when gateway_reference is empty", () => {
    const fields = extractTapFields(tapChargeFixtureEmptyGateway)!;
    const hashstring = buildTapHashstring(fields);
    const sig = crypto.createHmac("sha256", tapSecretKey).update(hashstring).digest("hex");
    expect(verifyTapWebhook(tapChargeFixtureEmptyGateway, sig, tapSecretKey)).toBe(true);
  });

  it("rejects when TAP_SECRET_KEY is not configured (fail closed)", () => {
    const fields = extractTapFields(tapChargeFixture)!;
    const hashstring = buildTapHashstring(fields);
    const sig = crypto.createHmac("sha256", tapSecretKey).update(hashstring).digest("hex");
    expect(verifyTapWebhook(tapChargeFixture, sig, undefined)).toBe(false);
    expect(verifyTapWebhook(tapChargeFixture, sig, "")).toBe(false);
  });

  it("rejects when hashstring header is missing", () => {
    expect(verifyTapWebhook(tapChargeFixture, undefined, tapSecretKey)).toBe(false);
    expect(verifyTapWebhook(tapChargeFixture, "", tapSecretKey)).toBe(false);
  });

  it("rejects a signature computed from the raw JSON body (NOT hashstring)", () => {
    // Attacker signs the raw body instead of the hashstring
    const rawBody = JSON.stringify(tapChargeFixture);
    const wrongSig = crypto.createHmac("sha256", tapSecretKey).update(rawBody).digest("hex");
    expect(verifyTapWebhook(tapChargeFixture, wrongSig, tapSecretKey)).toBe(false);
  });

  it("rejects a signature with wrong amount precision", () => {
    // Attacker uses "100" instead of "100.00"
    const wrongHashstring =
      "x_idchg_TS01A3BCDEFG" +
      "x_amount100" + // wrong precision
      "x_currencySAR" +
      "x_gateway_reference87654321" +
      "x_payment_referencepay_2024ABCDE" +
      "x_statusCAPTURED" +
      "x_created2024-12-15T10:30:00.000Z";
    const wrongSig = crypto.createHmac("sha256", tapSecretKey).update(wrongHashstring).digest("hex");
    expect(verifyTapWebhook(tapChargeFixture, wrongSig, tapSecretKey)).toBe(false);
  });

  it("rejects a signature with tampered status", () => {
    const fields = extractTapFields(tapChargeFixture)!;
    const tamperedHashstring = buildTapHashstring({ ...fields, status: "FAILED" });
    const tamperedSig = crypto.createHmac("sha256", tapSecretKey).update(tamperedHashstring).digest("hex");
    expect(verifyTapWebhook(tapChargeFixture, tamperedSig, tapSecretKey)).toBe(false);
  });

  it("rejects when payload is missing required fields", () => {
    const incompletePayload = { id: "chg_1", status: "CAPTURED" };
    const sig = crypto.createHmac("sha256", tapSecretKey).update("x").digest("hex");
    expect(verifyTapWebhook(incompletePayload, sig, tapSecretKey)).toBe(false);
  });

  it("uses the SAME key for API auth and webhook verification", () => {
    const fields = extractTapFields(tapChargeFixture)!;
    const hashstring = buildTapHashstring(fields);
    const sig = crypto.createHmac("sha256", tapSecretKey).update(hashstring).digest("hex");
    expect(verifyTapWebhook(tapChargeFixture, sig, tapSecretKey)).toBe(true);
    const differentKey = "sk_live_YYYYYYYYYYYYYYYYYYYY";
    expect(verifyTapWebhook(tapChargeFixture, sig, differentKey)).toBe(false);
  });
});

// ====================================================================
// Regression tests: the OLD (incorrect) implementations must be rejected
// ====================================================================

describe("webhook: Tap — rejects OLD incorrect implementations", () => {
  const tapSecretKey = "sk_test_XXXXXXXXXXXXXXXXXXXXXX";

  it("rejects a payload using flat gateway_reference (old shape)", () => {
    // OLD shape: gateway_reference was a top-level field
    // CORRECT shape: gateway_reference is reference.gateway
    const oldShapePayload = {
      id: "chg_TS01A3BCDEFG",
      amount: 100.00,
      currency: "SAR",
      gateway_reference: "87654321", // WRONG: should be reference.gateway
      reference: { payment: "pay_2024ABCDE" },
      status: "CAPTURED",
      transaction: { created: "2024-12-15T10:30:00.000Z" },
    };
    // The old shape payload should extract gateway_reference as "" (because
    // reference.gateway is absent), NOT "87654321" (which is the flat field
    // we no longer read). So a signature built from the OLD shape will fail.
    const fields = extractTapFields(oldShapePayload)!;
    expect(fields.gateway_reference).toBe(""); // flat field is ignored

    // If an attacker builds a hashstring using the OLD flat field value...
    const oldHashstring =
      "x_idchg_TS01A3BCDEFG" +
      "x_amount100.00" +
      "x_currencySAR" +
      "x_gateway_reference87654321" + // uses the flat field value
      "x_payment_referencepay_2024ABCDE" +
      "x_statusCAPTURED" +
      "x_created2024-12-15T10:30:00.000Z";
    const oldSig = crypto.createHmac("sha256", tapSecretKey).update(oldHashstring).digest("hex");
    // ...our verification should REJECT it because we extract "" not "87654321"
    expect(verifyTapWebhook(oldShapePayload, oldSig, tapSecretKey)).toBe(false);
  });

  it("rejects a payload using reference.transaction (old shape) instead of reference.payment", () => {
    // OLD shape: payment_reference was reference.transaction
    // CORRECT shape: payment_reference is reference.payment
    const oldShapePayload = {
      id: "chg_TS01A3BCDEFG",
      amount: 100.00,
      currency: "SAR",
      reference: {
        gateway: "87654321",
        transaction: "txn_2024ABCDE", // WRONG: should be payment
      },
      status: "CAPTURED",
      transaction: { created: "2024-12-15T10:30:00.000Z" },
    };
    // extractTapFields should return null because reference.payment is missing
    const fields = extractTapFields(oldShapePayload);
    expect(fields).toBeNull();
  });

  it("rejects a payload using flat created (old shape) instead of transaction.created", () => {
    // OLD shape: created was a top-level field
    // CORRECT shape: created is transaction.created
    const oldShapePayload = {
      id: "chg_TS01A3BCDEFG",
      amount: 100.00,
      currency: "SAR",
      reference: { gateway: "87654321", payment: "pay_2024ABCDE" },
      status: "CAPTURED",
      created: "2024-12-15T10:30:00.000Z", // WRONG: should be transaction.created
      // transaction is missing
    };
    // extractTapFields should return null because transaction.created is missing
    const fields = extractTapFields(oldShapePayload);
    expect(fields).toBeNull();
  });

  it("rejects a signature built with values.join('x') when gateway_reference is empty", () => {
    // The OLD implementation used values.join("x"). When gateway_reference
    // is "", join produces the same output as literal concatenation — BUT
    // only because join inserts "x" between elements. The literal form
    // is "x_gateway_reference" + "" + "x_payment_reference" which equals
    // "x_gateway_referencex_payment_reference". join would produce the same.
    //
    // However, the OLD implementation extracted gateway_reference from
    // payload.gateway_reference (flat) which would be undefined → null →
    // rejected. So the OLD implementation would REJECT a valid Tap
    // payload that has empty gateway_reference.
    //
    // This test documents that our NEW implementation ACCEPTS it.
    const fields = extractTapFields(tapChargeFixtureEmptyGateway)!;
    const hashstring = buildTapHashstring(fields);
    const sig = crypto.createHmac("sha256", tapSecretKey).update(hashstring).digest("hex");
    expect(verifyTapWebhook(tapChargeFixtureEmptyGateway, sig, tapSecretKey)).toBe(true);
  });
});

describe("webhook: amount verification", () => {
  it("accepts matching amounts", () => {
    expect(verifyAmount(89900, 89900)).toBe(true);
  });

  it("rejects mismatched amounts", () => {
    expect(verifyAmount(89900, 89999)).toBe(false);
    expect(verifyAmount(89900, 0)).toBe(false);
  });

  it("rejects NaN/Infinity", () => {
    expect(verifyAmount(NaN, 89900)).toBe(false);
    expect(verifyAmount(89900, Infinity)).toBe(false);
  });
});

describe("webhook: currency verification", () => {
  it("accepts matching currency (case-insensitive)", () => {
    expect(verifyCurrency("SAR", "SAR")).toBe(true);
    expect(verifyCurrency("sar", "SAR")).toBe(true);
    expect(verifyCurrency("SAR", "sar")).toBe(true);
  });

  it("rejects mismatched currency", () => {
    expect(verifyCurrency("SAR", "USD")).toBe(false);
    expect(verifyCurrency("SAR", "")).toBe(false);
  });
});

describe("webhook: metadata binding", () => {
  it("accepts matching userId + courseId", () => {
    expect(
      verifyPaymentMetadata(
        { userId: "u1", courseId: "c1" },
        { userId: "u1", courseId: "c1" }
      )
    ).toBe(true);
  });

  it("accepts when gateway omits metadata fields", () => {
    expect(
      verifyPaymentMetadata(
        { userId: "u1", courseId: "c1" },
        {}
      )
    ).toBe(true);
  });

  it("rejects userId mismatch", () => {
    expect(
      verifyPaymentMetadata(
        { userId: "u1", courseId: "c1" },
        { userId: "u2", courseId: "c1" }
      )
    ).toBe(false);
  });

  it("rejects courseId mismatch", () => {
    expect(
      verifyPaymentMetadata(
        { userId: "u1", courseId: "c1" },
        { userId: "u1", courseId: "c2" }
      )
    ).toBe(false);
  });
});

describe("webhook: gateway configuration check", () => {
  beforeEach(() => {
    vi.stubEnv("MOYASAR_SECRET_KEY", "");
    vi.stubEnv("TAP_SECRET_KEY", "");
  });
  afterEach(() => vi.unstubAllEnvs());

  it("returns false when MOYASAR_SECRET_KEY missing", () => {
    expect(isGatewayConfigured("moyasar")).toBe(false);
  });

  it("returns true when MOYASAR_SECRET_KEY set", () => {
    vi.stubEnv("MOYASAR_SECRET_KEY", "sk_test_xxx");
    expect(isGatewayConfigured("moyasar")).toBe(true);
  });

  it("returns false when TAP_SECRET_KEY missing", () => {
    expect(isGatewayConfigured("tap")).toBe(false);
  });

  it("returns true when TAP_SECRET_KEY set", () => {
    vi.stubEnv("TAP_SECRET_KEY", "sk_test_xxx");
    expect(isGatewayConfigured("tap")).toBe(true);
  });
});

describe("webhook: idempotency", () => {
  it("treats PAID as already-processed", () => {
    expect(isAlreadyPaid("PAID")).toBe(true);
  });

  it("treats PENDING / FAILED as not-paid", () => {
    expect(isAlreadyPaid("PENDING")).toBe(false);
    expect(isAlreadyPaid("FAILED")).toBe(false);
    expect(isAlreadyPaid("")).toBe(false);
  });
});
